name: NHL Predictions Daily Runner

on:
  schedule:
    - cron: '0 11 * * *'  # Runs daily at 11:00 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.create-pr.outputs.pr_number }}
    env:
      NHL_OPENAI_API_KEY: ${{ secrets.NHL_OPENAI_API_KEY }}
      NHL_ENGINE_NAME: ${{ secrets.NHL_ENGINE_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python app
        run: python src/main.py

      - name: Create and switch to a new branch
        run: git checkout -b update-predictions-${{ github.run_id }}

      - name: Commit changes
        run: |
          git config --local user.name 'StevenWangler'
          git config --local user.email 'Wangler.Steven@outlook.com'
          git add src/predictions.json
          git commit -m "Update daily prediction" -a || echo "No changes to commit"

      - name: Push changes
        run: git push origin update-predictions-${{ github.run_id }}
        
      - name: Create Pull Request
        id: create-pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GH_PAT }}
          pr_title: "Update daily prediction"
          pr_body: "Automated PR to update predictions.json"
          source_branch: "update-predictions-${{ github.run_id }}"
          destination_branch: "main"

      - name: Add automerge label to PR
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GH_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ steps.create-pr.outputs.pr_number }}/labels" \
          -d '{"labels":["automerge"]}'

