name: Auto Merge PR

on:
  schedule:
    - cron: '10 16 * * *'  # Runs daily at 11:10 AM EST (16:10 UTC)
  workflow_dispatch:  # Allows manual triggering
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          MERGE_METHOD: squash
          