name: Auto-Approve and Merge PR

on:
  schedule:
    - cron: '10 16 * * *'  # Runs daily at 11:10 AM EST (16:10 UTC)
  workflow_dispatch:  # Allows manual triggering
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve PR
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GH_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews" \
          -d '{"event":"APPROVE"}'
      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
