name: Auto Merge PR

on:
  schedule:
    - cron: '10 16 * * *'  # Runs daily at 11:10 AM EST (16:10 UTC)
  workflow_dispatch:  # Allows manual triggering
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          mergeMethod: squash # or 'merge' or 'rebase'
          # Additional conditions can be added here
          # requiredLabels: ["automerge"]
          # requiredChecks: ["ci-build"]
